name: Orange Pi 3B Coptra Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-orange-pi-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Orange Pi 3B Coptra image
        run: |
          # Make scripts executable
          chmod +x builder/*.sh
          # Run build in Docker
          docker run --privileged --rm -v /dev:/dev -v $(pwd):/builder/repo -e TRAVIS_TAG="${{ github.event.release.tag_name }}" sfalexrog/img-tool:qemu-update
      - name: Compress Orange Pi image
        run: |
          cd images && sudo chmod -R 777 . && zip -9 $(echo *_*).zip *_* && ls -l . && unzip -l *_*.zip
      - name: Upload Orange Pi image
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/*_*.zip
          prerelease: false
          body: |
            ## Orange Pi 3B Coptra Image
            
            ### Features:
            - Debian Bookworm with kernel 5.10
            - ROS Noetic for Orange Pi 3B
            - WiFi Access Point mode (SSID: coptra-XXXX)
            - Web interface for network configuration
            - Butterfly terminal server
            - Nginx web server
            
            ### Installation:
            1. Download and extract the image
            2. Flash to microSD card using balenaEtcher or similar
            3. Insert SD card into Orange Pi 3B
            4. Power on and connect to WiFi "coptra-XXXX" (password: coptrawifi)
            5. Access web interface at http://192.168.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}