name: Orange Pi 3B Coptra Image (Alternative)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-orange-pi-image-alt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support unzip ca-certificates curl wget
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Build Orange Pi 3B Coptra image (Alternative)
        run: |
          # Make scripts executable
          chmod +x builder/image-build.sh
          chmod +x builder/image-*.sh
          chmod +x builder/assets/*.sh
          
          # Use Ubuntu 22.04 with QEMU support
          docker run --privileged --rm \
            -v /dev:/dev \
            -v $(pwd):/builder/repo \
            -e TRAVIS_TAG="${{ github.event.release.tag_name }}" \
            -e IMAGE_VERSION="${{ github.event.release.tag_name || 'dev' }}" \
            -e DEBIAN_FRONTEND=noninteractive \
            -e TZ=UTC \
            ubuntu:22.04 \
            bash -c "
              # Install required packages
              apt-get update && apt-get install -y \
                qemu-user-static binfmt-support \
                unzip wget curl ca-certificates \
                kpartx parted dosfstools \
                git build-essential \
                python3 python3-pip
              
              # Setup QEMU for ARM64
              update-binfmts --enable qemu-arm
              update-binfmts --enable qemu-aarch64
              
              # Copy QEMU binaries
              cp /usr/bin/qemu-arm-static /usr/bin/qemu-aarch64-static 2>/dev/null || true
              
              # Fix Git security issue
              git config --global --add safe.directory /builder/repo
              
              # Navigate to repo and run build script
              cd /builder/repo && chmod +x builder/image-build.sh && ./builder/image-build.sh
            "
      
      - name: Compress image
        run: |
          cd images && sudo chmod -R 777 . 
          # Create archive with Orange Pi specific naming
          for img in *.img; do
            if [ -f "$img" ]; then
              zip -9 "coptra-orange-pi3b-$(basename $img .img).zip" "$img"
            fi
          done
          ls -l . && unzip -l *.zip
      
      - name: Upload Orange Pi image
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/coptra-orange-pi3b-*.zip
          prerelease: false
          body: |
            ## Orange Pi 3B Coptra Image ${{ github.event.release.tag_name }} (Alternative Build)
            
            ### Features:
            - ROS Noetic for Orange Pi 3B
            - WiFi Access Point mode (SSID: coptra-XXXX)
            - Web interface for network configuration
            - OV5647 camera support
            - Butterfly terminal server
            - Nginx web server
            
            ### Installation:
            1. Download and extract the image
            2. Flash to microSD card using balenaEtcher or similar
            3. Insert SD card into Orange Pi 3B
            4. Power on and connect to WiFi "coptra-XXXX" (password: coptrawifi)
            5. Access web interface at http://192.168.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
