name: Orange Pi 3B Coptra Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-orange-pi-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support unzip ca-certificates curl wget
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Build Orange Pi 3B Coptra image
        run: |
          # Make scripts executable
          chmod +x builder/image-build.sh
          chmod +x builder/image-*.sh
          chmod +x builder/assets/*.sh
          
          # Verify script permissions and structure
          ls -la builder/image-build.sh
          echo "=== Directory structure ==="
          ls -la builder/
          ls -la builder/assets/
          echo "=== Script content check ==="
          head -20 builder/image-build.sh
          
          # Use custom Docker image with ARM64 emulation for Orange Pi
          docker run --privileged --rm \
            -v /dev:/dev \
            -v $(pwd):/builder/repo \
            -e TRAVIS_TAG="${{ github.event.release.tag_name }}" \
            -e IMAGE_VERSION="${{ github.event.release.tag_name || 'dev' }}" \
            -e DEBIAN_FRONTEND=noninteractive \
            -e TZ=UTC \
            sfalexrog/img-tool:qemu-update \
            bash -c "cd /builder/repo && chmod +x builder/image-build.sh && ./builder/image-build.sh"
      
      - name: Compress image
        run: |
          cd images && sudo chmod -R 777 . 
          # Create archive with Orange Pi specific naming
          for img in *.img; do
            if [ -f "$img" ]; then
              zip -9 "coptra-orange-pi3b-$(basename $img .img).zip" "$img"
            fi
          done
          ls -l . && unzip -l *.zip
      
      - name: Upload Orange Pi image
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/coptra-orange-pi3b-*.zip
          prerelease: false
          body: |
            ## Orange Pi 3B Coptra Image ${{ github.event.release.tag_name }}
            
            ### Features:
            - ROS Noetic for Orange Pi 3B
            - WiFi Access Point mode (SSID: coptra-XXXX)
            - Web interface for network configuration
            - OV5647 camera support
            - Butterfly terminal server
            - Nginx web server
            
            ### Installation:
            1. Download and extract the image
            2. Flash to microSD card using balenaEtcher or similar
            3. Insert SD card into Orange Pi 3B
            4. Power on and connect to WiFi "coptra-XXXX" (password: coptrawifi)
            5. Access web interface at http://192.168.11.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
