name: RPi image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make scripts executable
        run: |
          chmod +x builder/*.sh
          chmod +x builder/assets/*.sh
      - name: Setup QEMU for ARM emulation
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build image
        run: |
          docker run --privileged --rm -v /dev:/dev -v $(pwd):/builder/repo -e TRAVIS_TAG="${{ github.event.release.tag_name }}" --platform linux/amd64 sfalexrog/img-tool:qemu-update
      - name: Compress image
        run: |
          cd images && sudo chmod -R 777 . && zip -9 $(echo *_*).zip *_* && ls -l . && unzip -l *_*.zip
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: images/
          retention-days: 30
      
      - name: Upload image to release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/*_*.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}