name: RPi image

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Make scripts executable
        run: |
          chmod +x builder/*.sh
          chmod +x builder/assets/*.sh
      - name: Setup QEMU for ARM emulation
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static binfmt-support
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Build image
        run: |
          docker run --privileged --rm -v /dev:/dev -v $(pwd):/builder/repo -e TRAVIS_TAG="${{ github.event.release.tag_name }}" --platform linux/amd64 sfalexrog/img-tool:qemu-update
      - name: Compress image
        run: |
          cd images && sudo chmod -R 777 . && zip -9 coptra-ros-image.zip coptra-ros_*.img && ls -l . && unzip -l coptra-ros-image.zip
      # Skip artifacts upload due to storage quota - use release instead
      - name: Create development release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'release' }}
        with:
          tag_name: dev-${{ github.sha }}
          name: Development Build ${{ github.sha }}
          files: images/coptra-ros-image.zip
          prerelease: true
          body: |
            Automated development build from commit ${{ github.sha }}
            Branch: ${{ github.ref_name }}
            Built: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Upload image to release
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'release' }}
        with:
          files: images/coptra-ros-image.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}